---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template to produce an imagestream and buildconfig for a Jlinked intermediate image
  name: s2i-build-template
parameters:
- name: APP_NAME
  description: Name of the application
  required: true
- name: GIT_URI
  description: Git repository URL
  required: true
- name: GIT_REF
  description: Git branch or tag to build
  required: true
- name: CONTEXT_DIR
  description: Context directory which is a directory within git repo
  required: true
- name: OUTPUT_IMAGE_TAG
  description: Tag for the output image
  required: true
- name: S2I_DELETE_SOURCE
  description: #place holder
  required: true
- name: LOGGING_SCRIPT_DEBUG
  description: #place holder
  required: true
- name: QUARKUS_PACKAGE_TYPE
  description: #place holder
  required: true
- name: JDK_VERSION
  description: #place holder
  required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-${JDK_VERSION}
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}-s2i-build
  spec:
    source:
      type: Git
      git:
        uri: ${GIT_URI}
        ref: ${GIT_REF}
        contextDir: ${CONTEXT_DIR}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ubi9-openjdk-${JDK_VERSION}-jlink:latest
          namespace: phase-1
          pullPolicy: Always  # equivalent for --pull-policy
        env:
          - name: S2I_DELETE_SOURCE
            value: ${S2I_DELETE_SOURCE}
          - name: LOGGING_SCRIPT_DEBUG
            value: ${LOGGING_SCRIPT_DEBUG}
          - name: QUARKUS_PACKAGE_TYPE
            value: ${QUARKUS_PACKAGE_TYPE}
          - name: DEBUG    # equivalent for --loglevel
            value: "5"
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}-${JDK_VERSION}:${OUTPUT_IMAGE_TAG}
