#!/bin/bash

# Command line arguments given to this script
args="$*"

source "${JBOSS_CONTAINER_UTIL_LOGGING_MODULE}/logging.sh"
source "${JBOSS_CONTAINER_S2I_CORE_MODULE}/s2i-core"
# include our s2i_core_*() overrides/extensions
source "${JBOSS_CONTAINER_JAVA_S2I_MODULE}/s2i-core-hooks"

# Global S2I variable setup
s2i_core_env_init

if [ -f "${JBOSS_CONTAINER_JOLOKIA_MODULE}/jolokia-opts" ]; then
    # Always include jolokia-opts, which can be empty if switched off via env
    S2I_RUN_OPTS="${S2I_RUN_OPTS} $(${JBOSS_CONTAINER_JOLOKIA_MODULE}/jolokia-opts)"
fi
if [ -f "${JBOSS_CONTAINER_PROMETHEUS_MODULE}/prometheus-opts" ]; then
    S2I_RUN_OPTS="${S2I_RUN_OPTS} $(source ${JBOSS_CONTAINER_PROMETHEUS_MODULE}/prometheus-opts && get_prometheus_opts)"
fi

export S2I_RUN_OPTS

# XXX this is needed to support a user-provided alternative run script but we
# should probably export all relevant S2I variables, possibly by moving the
# above `source` statements into run-java.sh
export S2I_TARGET_DEPLOYMENTS_DIR

exec "${JBOSS_CONTAINER_JAVA_RUN_MODULE}/run-java.sh" $args
