name: UBI9 OpenJDK S2I Image CI template
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
env:
  LANG: en_US.UTF-8
  IMAGE_URI: ghcr.io/jboss-container-images/${{ inputs.image }}:${{ github.ref_name }}
jobs:
  openjdkci:
    permissions:
      packages: write
    name: OpenJDK S2I Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Verify latest UBI image is present
        run:  docker pull registry.access.redhat.com/ubi9/ubi-minimal:latest

      - name: Install CEKit
        uses: cekit/actions-setup-cekit@v1.1.5

      - name: Build
        run: |
          cekit -v --descriptor ${{ inputs.image }}.yaml build docker --no-squash --tag localimage

      - name: Install and cache S2I CLI tool from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: "github"
          github_pat: ${{ github.token }}
          s2i: "1.3.4"

      - name: Behave Tests
        run: |
          echo /home/runner/work/_temp/openshift-bin >> $GITHUB_PATH
          cekit -v --descriptor ${{ inputs.image }}.yaml test --image localimage behave

      - if: github.event_name == 'push'
        name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - if: github.event_name == 'push'
        name: Tag and push container image
        run: |
          docker tag localimage ${{ env.IMAGE_URI }}
          docker push ${{ env.IMAGE_URI }}
