name: UBI9 OpenJDK 21 Runtime S2I Image CI
on: [push, pull_request]
env:
  LANG: en_US.UTF-8
  IMAGE: openjdk-21-jlink-rhel9-runtime
jobs:
  call-openjdkci:
    uses: ./.github/workflows/image-workflow-template.yml
    with:
      image: openjdk-21-jlink-rhel9-runtime
